store:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/store
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: 1VzBnS3kxAnq36K3byWRcNqlfPFK3iji
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt